language: node_js
node_js:
  - "4.4"
branches:
  only:
    - master
before_install:
  - npm install -g gulp
  - npm install -g resume-cli
install:
  - npm install
before_script:
  - npm link
script:
  - gulp
  - resume test
  - resume export caffeine-resume.pdf --format pdf --theme caffeine
  - rm caffeine-resume.pdf